#!/usr/bin/env python3
"""Place the opcode handlers named in iram_handlers.txt in internal RAM.

cpuemu.cpp is generated by gencpu; generate_cpu_tables.sh runs this step
afterwards. Every handler definition gets IRAM_ATTR exactly when it is
listed, so the list is the single source of truth and reruns are no-ops.
"""

from pathlib import Path
import re
import sys

HERE = Path(__file__).resolve().parent
DEFAULT_SOURCE = HERE.parents[1] / "src/basilisk/uae_cpu/generated/cpuemu.cpp"
DEFINITION = re.compile(r"^(IRAM_ATTR )?(void REGPARAM2 CPUFUNC\((op_[0-9a-f]+_[0-9]+)\)\(uae_u32 opcode\))", re.M)


def main() -> int:
    source = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SOURCE
    listed = {
        line.strip()
        for line in (HERE / "iram_handlers.txt").read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }
    text = source.read_text()
    found = set()

    def annotate(match: re.Match) -> str:
        name = match.group(3)
        if name in listed:
            found.add(name)
            return "IRAM_ATTR " + match.group(2)
        return match.group(2)

    updated = DEFINITION.sub(annotate, text)
    missing = sorted(listed - found)
    if missing:
        print("unknown handlers in iram_handlers.txt: " + ", ".join(missing), file=sys.stderr)
        return 1
    if updated != text:
        source.write_text(updated)
    print(f"{len(found)} handlers in IRAM")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
